#' @keywords internal
"_PACKAGE"

if (getRversion() >= "2.15.1")
  utils::globalVariables(
    c(".",
      ":=",
      "Age: <15/15+ (Coarse)",
      "Age: <15\\/15+ \\(Coarse\\)",
      "agecoarse",
      "agency",
      "Cascade sex",
      "code",
      "community",
      "coordinates",
      "country_name",
      "Disaggregation Type",
      "displayName",
      "full_path",
      "Funding Agency",
      "Funding Mechanism",
      "fundingagency",
      "fy",
      "fy_drop",
      "hfr_pd",
      "hfr_pd_drop",
      "HIV Test Status (Specific)",
      "id",
      "ind",
      "indicator",
      "iso_map",
      "longitude",
      "mech_code",
      "mech_name",
      "mech_name_d",
      "mech_uid",
      "mechanism",
      "mechanismid",
      "mer_results",
      "mer_targets",
      "mtype",
      "name",
      "name3",
      "name4",
      "newest",
      "operatingunit",
      "Organisation unit",
      "orglvl_1",
      "orglvl_2",
      "orglvl_3",
      "orglvl_4",
      "orgunit",
      "orgunit_d",
      "orgunituid",
      "orgunituid_d",
      "otherdisaggregate",
      "ou",
      "ou_name",
      "partner",
      "path",
      "Period",
      "primepartner",
      "primepartner_d",
      "psnu",
      "psnu_d",
      "region_uids",
      "sex",
      "snu1",
      "Targets / Results",
      "targets_gap",
      "Technical Area",
      "template_cols_meta",
      "type",
      "usaid_only",
      "val",
      "value",
      "Value",
      "weekly_targets",
      "weekly_targets_gap")

  )
